sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
      - udf_coverage # works for our Maven plugin integration tests too (even if there is no UDF in this project).
